locale/de/helmod.cfg
locale/de/settings.cfg

Without Tooltiptranslation and everyday ingame usage not confirmed.
Maybe added soon

German Translation v0.9

---

locale/en/helmod.cfg

Fix tooltip for recipes and button text for exiting a production block.

Update English Locale

---

model/RecipePrototype.lua

Added RecipePrototype::getRawProducts with old getProducts functionality
Changed RecipePrototype::getProducts to combine identical products in output
I've tested this by creating production blocks using the problematic recipe from Angel's Bioprocessing, but haven't yet gone through all the callers of getProducts to make sure none of them will be thrown off by the change. As long as none of them care how the returned table is indexed, there shouldn't be any new problems.

Fix #141 and #124 by combining recipe outputs for same product

---

info.json
lib/crc32lua.lua
lib/deflatelua.lua
lib/zlib-deflate.lua
prototypes/style.lua

This is my take on porting the mod to Factorio v0.17.
This was mentioned in #163 .
I can't test yet if everything works... Maybe someone else can look at it ingame?
Best regards
jodli

Factorio 0.17

---

core/defines.lua

Cause I want to use tier 5 or 6 and not 7.

Add tier 5 and 6 to settings

---

locale/en/help.cfg

Updated some wording for better help readability in english.

Better english wording

---

locale/ru/helmod.cfg

Update Russian translation to actual version

Update to Helmod v0.9.8

---

locale/en/helmod.cfg
locale/ru/helmod.cfg

It's already there in fr, but is wrong in the others.

Put priority-modules in expected section

---

controller/Controller.lua
core/Format.lua
core/defines.lua
data/Model.lua
data/ModelBuilder.lua
data/ModelCompute.lua
data/User.lua
edition/PreferenceEdition.lua
edition/RecipeEdition.lua
gui/GuiCell.lua
gui/GuiTooltip.lua
info.json
locale/en/helmod.cfg
locale/en/settings.cfg
locale/fr/helmod.cfg
locale/fr/settings.cfg
locale/ru/helmod.cfg
model/EntityPrototype.lua
tab/AbstractTab.lua
tab/ProductionBlockTab.lua
tab/ProductionLineTab.lua

Features:
- Added option to activate or disable pollution information
Changes:
- Changed pollution to display value, per minute in tooltip
- Changed preference panel
- Moved few mod settings in the preference panel
Bugfixes:
- fixed copy/past block for fuel and module
- fixed default factory from mod setting and the default set at 1

Changed preference panel

---

changelog.txt
data/Cache.lua
data/Model.lua
data/ModelCompute.lua
edition/PreferenceEdition.lua
gui/GuiCell.lua
gui/GuiTooltip.lua
info.json
locale/en/helmod.cfg
locale/fr/helmod.cfg
model/EntityPrototype.lua
model/Player.lua
model/Product.lua
tab/AbstractTab.lua
tab/ProductionBlockTab.lua
tab/PropertiesTab.lua

Features:
- Added inserter in logistic information
Bugfixes:
- fixed crafting-handonly recipe, player replaced by character
- fixed tooltip product in the pinned panel
- removed cache variable can MP desync
- fixed arithemtic error on pollution

Added inserter in logistic information

---

changelog.txt
controller/Controller.lua
core/Form.lua
core/defines.lua
core/logging.lua
data/ModelCompute.lua
data/User.lua
edition/RecipeEdition.lua
gui/GuiCell.lua
gui/GuiLabel.lua
gui/GuiTooltip.lua
info.json
locale/en/helmod.cfg
locale/en/settings.cfg
locale/fr/helmod.cfg
locale/fr/settings.cfg
model/BurnerPrototype.lua
model/EntityPrototype.lua
model/FluidPrototype.lua
model/FluidboxPrototype.lua
model/Player.lua
model/PrototypeFilter.lua
model/RecipePrototype.lua
model/Technology.lua
selector/AbstractSelector.lua
selector/RecipeSelector.lua
tab/AdminTab.lua
tab/PropertiesTab.lua
tab/PrototypeFiltersTab.lua

Changes:
- generate user cache on several tick
- added error if recursive event > 6000
- added fluid fuel for factory
- change display module of factory
- added response on ENTER in the filter input of selector
Bugfixes:
- fixed recipe not appear in recipe selector when researched
- fixed some bug in properties tab
- fixed generate user cache when auto pause is activate
- fixed crash on new game

generate user cache on several tick

---

locale/ru/helmod.cfg

Update russian locale helmog.cfg to v0.10.25

Update to v0.10.25

---

changelog.txt
dialog/ProductionPanel.lua
edition/LogisticEdition.lua
edition/ModelEdition.lua
edition/PreferenceEdition.lua
edition/ProductEdition.lua
edition/RecipeEdition.lua
edition/RuleEdition.lua
info.json

+  Bugfixes:
- Fixed changelog error
- Fixed missing height style for product list in output and input
- Fixed delete block in production line view
- Fixed some edition views after minimize and maximize action

Fixed missing height style for product list in output and input

---

changelog.txt
core/Form.lua
data/ModelBuilder.lua
data/User.lua
dialog/Download.lua
dialog/HelpPanel.lua
dialog/ProductionPanel.lua
edition/ModelEdition.lua
edition/PreferenceEdition.lua
edition/RecipeEdition.lua
gui/GuiCell.lua
info.json
locale/en/helmod.cfg
locale/fr/helmod.cfg
selector/AbstractSelector.lua
selector/RecipeSelector.lua

Changes:
- Removed beacon column in production line view
Bugfixes:
- Fixed bug on factory column in production line view
- Fixed some panel display size problem

Fixed bug on factory column in production line view

---

changelog.txt
control.lua
controller/Controller.lua
controller/EventController.lua
core/Form.lua
core/defines.lua
core/tableExtends.lua
data/User.lua
dialog/AdminPanel.lua
dialog/HelpPanel.lua
dialog/ProductionPanel.lua
info.json
locale/en/helmod.cfg
locale/en/help.cfg
locale/en/settings.cfg
locale/fr/help.cfg
locale/fr/settings.cfg

Features:
- Added tips when open some panel
Bugfixes:
- Fixed clean top or left panel when helmod is the first

Added tips when open some panel

---

locale/en/help.cfg

I noticed some minor English issues in the Help texts

Minor fixes of English translations

---

changelog.txt
model/Player.lua
model/RecipePrototype.lua

Hidden boilers are shown

---

changelog.txt
edition/RecipeEdition.lua
info.json
model/Player.lua

Module issues

---

changelog.txt
data/ModelBuilder.lua

Fix "convert recipe to block" for "ingredient input"-mode
wrong recipes have been send to new block in ingredient input mode.

Fix convert recipe to block function

---

changelog.txt
data/Model.lua
selector/RecipeSelector.lua

Hide transport drones recipes

---

.gitignore
.vscode/launch.json
controller/Controller.lua
core/FormModel.lua
data/Model.lua
data/ModelBuilder.lua
data/ModelCompute.lua
data/User.lua
dialog/PinPanel.lua
dialog/ProductionPanel.lua
doc/runtime-api-model.lua
edition/RecipeEdition.lua
gui/GuiCell.lua
gui/GuiTooltip.lua
locale/de/helmod.cfg
locale/en/helmod.cfg
locale/fr/helmod.cfg
locale/ja/helmod.cfg
locale/ko/helmod.cfg
locale/ru/helmod.cfg
math/Solver.lua
math/SolverMatrix.lua
model/Player.lua
prototypes/style-frame.lua

new feature for use few beacons

Allow few Beacons

---

locale/es-ES/helmod.cfg
locale/es-ES/help.cfg
locale/es-ES/settings.cfg

Locale es-ES Helmod 2.0.22

---

controller/Controller.lua
data/Model.lua
dialog/ProductionPanel.lua
doc/runtime-api-model.lua
edition/BlockEdition.lua
gui/GuiCell.lua
locale/en/helmod.cfg

This *should* be the final PR for this.
Fixed #616 
See: #617 #618 #619

Block edition
